### ISSUE TITLE
[ Bug ] Oricorio, Oricorio Pom-Pom, Oricorio Pom-Pom Style Image Broken

### ISSUE THREAD

**Issue by vater1203** [Mantaro/MantaroBot#303] opened 2020-03-24 19:17 UTC
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
The image shows 1/4 of itself then the rest is jagged and glitchy....and yes... I tried refreshing the website....its the same jank image

**To Reproduce**
simply ~>game pokemon

**Expected behavior**
I simply expected a pokemon to appear

**Additional context**
my Discord IGN- vater1203#6504

**Comment by Kodehawa** [comment] 2020-03-24 19:18
replace this text with a response to a bug report

**Comment by Kodehawa** [comment] 2020-04-05 17:36
We're aware of this issue and would love to fix it but we believe it's caused by cloudflare cache rather than an issue on our end. We'll keep looking into it.

**Comment by Kodehawa** [comment] 2020-04-05 17:37
Also, closing because it's a duplicate of #303

**Comment by Kodehawa** [comment] 2020-11-17 18:48
Re-opening, the images are corrupted on our side. I noticed the issue and will close this issue once we confirm this is fixed.

**Comment by Kodehawa** [comment] 2020-11-17 19:31
*Actually* fixed now.

**Closed by Kodehawa** 2020-11-17 19:31 UTC
Labels: bug
