### ISSUE TITLE
bug ~>daily

### ISSUE THREAD

**Issue by zelda-epona** [Mantaro/MantaroBot#308] opened 2020-04-05 17:09 UTC
Hello !
The commande ~>daily is not working anymore on my server and when we use it now Montaro say :

"I think you forgot something on the floor. (Maybe we threw it there? Just in case, the error id is CaocgYSCAGg)
:warning: Could be an internal error, but check the command arguments or maybe the message I'm trying to send exceeds 2048 characters, Just in case, check command help! (Support server link can be found at support.mantaro.site)"

How can we fix that ?

**Comment by Kodehawa** [comment] 2020-04-05 17:18
What's your server language set as?

**Comment by Kodehawa** [comment] 2020-04-05 17:30
I can't seem to reproduce this issue, but I have a few questions:
- Do you have a custom language set? Is it french? If so, the cause is https://github.com/Mantaro/MantaroBot/commit/8de7be643845851ab0659250bbc445d50a6b4244#diff-6b3eeb32793535b9bb2c7850052f65a1L1519 and temporarly switching to another language might do the trick.
- Does it happen when giving it to yourself or to another person?

**Comment by zelda-epona** [comment] 2020-04-05 17:43
Yes we use french. I will try  to switch the langage. 
I don't realy understand your second point you can give your daily loot to someone ?
To explain, if someone on my discord use ~>daily (written just like that) then the message appear. 
(That issue started some hours ago)

**Comment by Kodehawa** [comment] 2020-04-05 17:44
Yeah. Just switch the server language for now. I'll close the issue whenever the issue it's fixed in prod.

Your daily was saved, so don't fear about losing it.

**Comment by zelda-epona** [comment] 2020-04-05 17:47
.............
Wait a minute.... It's working again.... Okai ; I did nothing but it's working again... xD Well... thanks for your time ; I will come back if the issue happen once more.... xD

**Closed** 2020-04-15 16:35 UTC

**Comment by Kodehawa** [comment] 2020-04-15 16:51
This has been fixed.
