### ISSUE TITLE
[ Bug ] Calling a custom command with the mantaro prefix breaks $(event.message)

### ISSUE THREAD

**Issue by PlatypodeCode** [Mantaro/MantaroBot#229] opened 2018-11-28 13:02 UTC
$(event.message) should exclude the command name from the raw text, however this is not the case when the command it contains is called through the mantaro prefix.
This has been tested also with both the .raw and .stripped variants.

**Comment by Kodehawa** [comment] 2018-12-15 00:07
We know what the issue is now, gonna be fixed on a future update.

**Comment by Kodehawa** [comment] 2019-09-14 19:23
Fixed on https://github.com/Mantaro/MantaroBot/commit/32023cea79ab68923c5a373561fd443d4bd845ba

**Closed by Kodehawa** 2019-09-14 19:23 UTC
Labels: bug, trello
